import './globals.css'
import type { Metadata } from 'next'
import { Inter, Pacifico } from 'next/font/google'
import Providers from './provider'

const inter = Inter({ subsets: ['latin'] })
const pacifico = Pacifico({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  )
}
